### ISSUE TITLE
Create a FHIR patient bundle for testing and script to add patient to SMART sandbox

### ISSUE THREAD

**Issue by jtquach1** [mcode/clinical-trial-matching-app#5]
An existing patient uploading script exists at https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/blob/master/src/utils/uploadTestPatients.js and we can use 2 example patients.

# Suggestion 1
For instance: 
https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/blob/fbb53d4cd35c07ed386211aa16e53ece41fb7a9d/src/utils/uploadTestPatients.js#L8-L14
can be changed to

```js
const SMART_HEALTH_IT_ENDPOINT = 'https://r4.smarthealthit.org';
const MOONSHOT_ENDPOINT = 'http://moonshot-dev.mitre.org:4006/baseR4';

// R4
upload('R4', SMART_HEALTH_IT_ENDPOINT, path.join(__dirname, 'r4_test_patients'));
upload('R4', MOONSHOT_ENDPOINT, path.join(__dirname, 'r4_test_patients'));
```

where one can comment out the `upload` calls however they see fit.

If we want to reuse this script in our repo, additional dependencies would be added like so in package.json:
https://github.com/mcode/clinical-trial-matching-app/blob/a5ab398bcd056c8c76da2c8958150cf74c639fb3/package.json#L36

```js
    "react-query": "^3.23.2",
    "request": "^2.34",
    "request-promise-native": "^1.0.9",
    "mkdirp": "^1.0.4"
```

And in the .gitignore:
https://github.com/mcode/clinical-trial-matching-app/blob/a5ab398bcd056c8c76da2c8958150cf74c639fb3/.gitignore#L19

```
.DS_Store
/test_patient_dump
```

Additionally, a `./src/utils/r4_test_patients` directory must be created (this stores the JSON patient bundles).

# Suggestion 2
Alternatively, one could 

1. Clone the repo at https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY
2. Install only the needed dependencies for running the patient upload script by running the command 
```
yarn add request-promise-native request mkdirp
```
3. Change https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/blob/fbb53d4cd35c07ed386211aa16e53ece41fb7a9d/src/utils/uploadTestPatients.js#L8-L14
to

```js
const SMART_HEALTH_IT_ENDPOINT = 'https://r4.smarthealthit.org';
const MOONSHOT_ENDPOINT = 'http://moonshot-dev.mitre.org:4006/baseR4';

// R4
upload('R4', SMART_HEALTH_IT_ENDPOINT, path.join(__dirname, 'r4_test_patients'));
upload('R4', MOONSHOT_ENDPOINT, path.join(__dirname, 'r4_test_patients'));
```
4. Add the desired FHIR Version 4 patient bundles to `./src/utils/r4_test_patients/` 
5. Run `yarn upload-test-patients`

**Comment by noranda** [comment]
I think the first suggestion makes sense for our needs.

**Comment by noranda** [comment]
> I'll make a PR shortly then. Do you think it's a good idea for me to convert the script to TypeScript as well?

Yes please!
